version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
